version: "3"

services:
  chalice-app:
    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock
      # Mount the root folder that contains .git
      # see: https://code.visualstudio.com/remote/advancedcontainers/connect-multiple-containers
      - .:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity

    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    # cap_add:
    #  - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

  next-app:
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - .:/workspaces:cached
      - node_modules:/workspaces/next-app/node_modules
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity

volumes:
  node_modules:
